### ISSUE TITLE
Why nats.io and fasthttp doesn't work together?

### ISSUE THREAD

**Issue by hiqbn** [gramework/gramework#63] opened 2019-01-02 17:51 UTC
my code is here:
https://pastebin.com/raw/hURatUqs

failed at 

         conn.WriteMessage(websocket.TextMessage []byte(s))

if will work if i comment 

               nc.Subscribe(subj, func(

so i don't understand why they cant work together

===================

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x75e3b2]

goroutine 61 [running]:
github.com/valyala/fasthttp.(*hijackConn).SetWriteDeadline(0xc007ef0a00, 0x0, 0x0, 0x0, 0xc0000aa000, 0x203001)
        <autogenerated>:1 +0x32
github.com/fasthttp/websocket.(*Conn).write(0xc0067dc420, 0x1, 0x0, 0x0, 0x0, 0xc007efa90c, 0x3, 0x402, 0xc0075156b1, 0x0, ...)
        /go/src/github.com/fasthttp/websocket/conn.go:376 +0xfb
github.com/fasthttp/websocket.(*messageWriter).flushFrame(0xc00680fec8, 0xc007515601, 0xc0075156b1, 0x0, 0x7, 0x8, 0xc0075156b0)
        /go/src/github.com/fasthttp/websocket/conn.go:601 +0x23d
github.com/fasthttp/websocket.(*Conn).WriteMessage(0xc0067dc420, 0x1, 0xc0075156b0, 0x1, 0x8, 0x8, 0x0)
        /go/src/github.com/fasthttp/websocket/conn.go:753 +0x24b
main.requestHandler.func1.1(0xc007f2c000)
        /usr/local/src/programs/r/r.go:496 +0xd1
github.com/nats-io/go-nats.(*Conn).waitForMsgs(0xc007f04000, 0xc0044003c0)
        /go/src/github.com/nats-io/go-nats/nats.go:2024 +0x258
created by github.com/nats-io/go-nats.(*Conn).subscribe
        /go/src/github.com/nats-io/go-nats/nats.go:2789 +0x460

**Comment by kirillDanshin** [comment] 2019-01-02 19:51
duplicate of https://github.com/fasthttp/websocket/issues/4. closing this issue in favor of fasthttp/websocket#4

your example related to fasthttp/websocket or nuts.io, not gramework :) @savsgio suggest a good idea, check it out there.

if you have any questions about gramework, feel free to ping me again.

kind regards.

**Closed as completed by kirillDanshin** 2019-01-02 19:51 UTC
